### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by opemvbs** [nazmifr/archive.org_booklet_scraper#1]
always seems to get error 403 forbidden, i have changed the user agent multiple times too

**Comment by opemvbs** [comment]
Seems like I got some solutions for this. In my case, I am downloading a 1000+ page book, so it takes time. After around a few minutes, the cookies expires, and that's why I got Error 403 Forbidden. To fix this I just re-generate my cookies by refreshing the archive.org site, and saving the cookies.txt, and editing my from:"pagenumber" into the next before the file that downloaded when 403 Forbidden happened. And just executing the .sh script again.

**Comment by nazmifr** [comment]
Hi there, I had some issues too, I'll check if the code is updated on the github repository. I think the user agent got banned for some reason, I'll be right back later tonight

**Comment by nazmifr** [comment]
Yes you may need to update the cookie every hundred pages or so, and each time change the range. This is normal behaviour !

**Comment by nazmifr** [comment]
I fixed the instructions to include your workaround. 

Fetching the cookies automatically with the script (and asking for the archive.org credentials) would be a clean solution but it's too cumbersome, at least for now, and borderline in terms of confidentiality (plain text file containing your password and archive.org ID :/ )

Contributions and other ideas welcome. And thank you for your feedback @opemvbs
